---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultstorerules.vault2kube.sorah.jp
spec:
  group: vault2kube.sorah.jp
  names:
    kind: VaultStoreRule
    plural: vaultstorerules
    shortNames:
    - vaultrule
    singular: vaultstorerule
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              destinationName:
                type: string
              renewBeforeSeconds:
                minimum: 0
                nullable: true
                type: number
              revokeAfterSeconds:
                default: 1
                minimum: 0
                nullable: true
                type: number
              rolloutRestarts:
                items:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                nullable: true
                type: array
              rotateBeforeSeconds:
                minimum: 0
                nullable: true
                type: number
              sourcePath:
                type: string
              templates:
                items:
                  properties:
                    key:
                      type: string
                    template:
                      type: string
                  type: object
                required:
                - key
                - template
                type: array
            required:
            - sourcePath
            - destinationName
            - templates
            type: object
          status:
            properties:
              expiresAt:
                nullable: true
                type: string
              lastLeaseId:
                nullable: true
                type: string
              lastRunStartedAt:
                nullable: true
                type: string
              lastSuccessfulRunAt:
                nullable: true
                type: string
              leaseId:
                nullable: true
                type: string
              nextLeaseId:
                nullable: true
                type: string
              rotatedAt:
                nullable: true
                type: string
              ttl:
                minimum: 0
                nullable: true
                type: number
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: vault2kube
  namespace: default
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: true
          containers:
          - command:
            - "/usr/bin/vault2kube"
            - run
            env:
            - name: VAULT_ADDR
              value: https://path.to.your.vault:8200
            - name: VAULT_K8S_PATH
              value: auth/kubernetes
            - name: VAULT_K8S_ROLE
              value: vault2kube
            - name: RUST_LOG
              value: info
            image: sorah/vault2kube:latest
            imagePullPolicy: Always
            name: vault2kube
          restartPolicy: Never
          serviceAccountName: vault2kube
  schedule: 18 */6 * * *
  successfulJobsHistoryLimit: 3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault2kube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault2kube
subjects:
- kind: ServiceAccount
  name: vault2kube
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault2kube
rules:
- apiGroups:
  - vault2kube.sorah.jp
  resources:
  - vaultstorerules
  verbs:
  - get
  - list
- apiGroups:
  - vault2kube.sorah.jp
  resources:
  - vaultstorerules/status
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault2kube
  namespace: default
